version: "3"

services:
  lab3-db:
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    image: postgres
    ports:
      - ${DB_PORT}:${DB_PORT}